[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
    "poetry-core>=1.0.0",
]

[dependency-groups]
dev = [
    "hypothesis>=6.122.3", # Property-based testing framework
    "pip>=24.3.1", # Package installer (latest version)
    "pyprojectsort>=0.3.0", # Sorts pyproject.toml files
    "pytest-cases>=3.8.6", # Advanced test parameterization
    "pytest-cov>=6.0.0", # Code coverage reporting
    "pytest-icdiff>=0.9", # Improved diff output for test failures
    "pytest-mock>=3.14.0", # Mocking support for testing
    "pytest-playwright>=0.6.2", # Browser automation testing
    "pytest-profiling>=1.8.1", # Test performance profiling
    "pytest-random-order>=1.1.1", # Randomized test execution
    "pytest-shutil>=1.8.1", # Filesystem utilities for testing
    "pytest-split>=0.10.0", # Parallel test execution
    "pytest-sugar>=1.0.0", # Enhanced test output formatting
    "pytest-timeout>=2.3.1", # Test execution timeout control
    "pytest>=8.3.4", # Core testing framework
    "tox>=4.23.2", # Test automation and virtual env management
    "uv>=0.5.7", # Fast Python package installer and resolver
    "ruff>=0.8.3",
    "bandit>=1.8.0",
    "pydoclint>=0.5.11",
    "pyinstrument>=5.0.0",
    "pyright>=1.1.390",
    "taplo>=0.9.3",
]
nb = [
    "chime>=0.7.0",
    "ipykernel>=6.29.5", # IPython kernel for Jupyter notebooks
    "ipython>=7.34.0", # Enhanced interactive Python shell
    "ipywidgets>=8.1.5", # Interactive widgets for notebooks
    "jupyterlab>=4.3.3", # Modern notebook development environment
]
dev-nb = [
    "jupyter-book>=1.0.3",
    "nbformat>=5.10.4",
    "nbqa>=1.9.1", # Code quality tools for notebooks
    "testbook>=0.4.2",
]
web = [
    "beautifulsoup4>=4.12.3",
    "fastapi>=0.115.6",
    "playwright>=1.49.1",
    "requests>=2.32.3",
    "uvicorn>=0.33.0",
    "zrok>=0.4.42",
]
config = [
    "cookiecutter>=2.6.0",
    "gin-config>=0.5.0",
    "jinja2>=3.1.4",
]
ai-apps = [
    "ell-ai>=0.0.15",
    "langchain>=0.3.12",
    "megaparse>=0.0.45",
]
ai-train = [
    "datasets>=3.1.0",
    "einops>=0.8.0",
    "jaxtyping>=0.2.36",
    "pytorch-lightning>=2.4.0",
    "safetensors>=0.4.5",
    "scikit-learn>=1.6.0",
    "torch>=2.5.1",
    "transformers>=4.47.0",
    "umap-learn>=0.5.7",
]
data = [
    "dagster>=1.9.5",
    "networkx>=3.4.2",
    "numpy>=1.26.4",
    "orjson>=3.10.12",
    "polars>=1.17.0",
    "tomli>=2.0.1",
]
dev-doc = [
    "mdformat>=0.7.19",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.48",
]
cli = [
    "typer>=0.15.1",
]

[project]
dependencies = [
    "loguru>=0.7.3",
    "loguru-config>=0.1.0",
    "plotly>=5.24.1",
    "polyfactory",
    "pydantic>=2.10.3",
    "rich>=13.9.4",
    "safetensors>=0.4.5",
    "scikit-learn",
    "tokenize-rt",
]
name = "embedding-translation"
requires-python = ">=3.11,<3.13"

[tool.poe.tasks.check]
help = "All checks"
ignore_fail = false
sequence = [
    "check-lock",
    "docstring-lint",
    "format",
    "lint",
    "test",
    "typecheck",
]

[tool.poe.tasks.docstring-lint]
cmd = "pydoclint ."
help = "Lint docstrings"

[tool.poe.tasks.format]
cmd = "ruff format ."
help = "Format code (with autofix)"

[tool.poe.tasks.lint]
cmd = "ruff check . --fix"
help = "Lint (with autofix)"

[tool.poe.tasks.test]
cmd = "pytest"
help = "Run tests"

[tool.poe.tasks.typecheck]
cmd = "pyright"
help = "Typecheck"

[tool.poetry]
authors = [
    "Gatlen Culp, Adriano Hernandez <GatlenCulp@gmail.com>",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
description = "A final project for MIT's Deep Learning class"
keywords = []
license = "MIT"
name = "embedding-translation"
packages = [
    { include = "owler_fork" },
    { include = "src" },
]
readme = "README.md"
repository = "https://github.com/GatlenCulp/embedding_translation"
version = "0.0"

[tool.poetry.dependencies]
# chime = "^0.7.0"
# datasets = "^3.1.0"
# einops = "^0.8.0"
# gin-config = "^0.5.0"
# ipykernel = "^6.29.5"
# ipython = "^7.12.0"
# ipywidgets = "^8.1.5"
# jaxtyping = "^0.2.36"
# loguru = "^0.7.3"
# loguru-config = "^0.1.0"
# networkx = "^3.4.2"
# numpy = "<2.0.0"
# orjson = "^3.10.12"
# plotly = "^5.24.1"
# poethepoet = "*"
# polars = "^1.16.0"
# pydantic = ">=1.10.8"
# python = ">=3.11,<3.13"
# rich = "^13.9.4"
# tomli = "*"
# transformers = "^4.47.0"
# typeguard = "^4.2.1"
# typer = "^0.15.1"
wrapt = "^1.17.0"

[tool.poetry.dev-dependencies]
# bandit = "^1.8.0"
# hypothesis = "^6.122.1"
# jupyter-book = "^1.0.3"
# mdformat = "^0.7.19"
# mkdocs = "^1.6.1"
# mkdocs-material = "^9.5.47"
# nbqa = "^1.9.1"
# poethepoet = "*"
# pydoclint = "*"
# pyinstrument = "*"
# pyright = "^1.1.390"
# pytest = "^8.1"
# pytest-cases = "^3.8.6"
# pytest-cov = "^6.0.0"
# pytest-icdiff = "^0.9"
# pytest-mock = "^3.14.0"
# pytest-playwright = "^0.6.2"
# pytest-profiling = "^1.8.1"
# pytest-random-order = "^1.1.1"
# pytest-shutil = "^1.8.1"
# pytest-split = "^0.10.0"
# pytest-sugar = "^1.0.0"
# pytest-timeout = "^2.3.1"
# ruff = "*"
# taplo = "^0.9.3"
# testbook = "^0.4.2"

[tool.poetry.scripts]
embedding_tranlation = "src:main"

[tool.pydoclint]
allow-init-docstring = true
arg-type-hints-in-docstring = false
check-return-types = false
exclude = "\\.venv"
style = "google"

[tool.pyright]
include = [
    ".",
]
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false

[tool.pytest.ini_options]
addopts = "--show-capture=no\n--code-highlight=yes\n--tb=long\n-rA\n-x\n--doctest-modules\n--cov=src\n--cov-report=html\n--cov-report=term-missing:skip-covered\n--no-cov-on-fail\n"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
    "ignore::pydantic.warnings.PydanticDeprecatedSince20",
]
markers = [
    "potentially_harmful: mark test as potentially harmful to the system (uninstalls, etc.)",
]
pythonpath = [
    "src",
]
testpaths = [
    "tests",
]

[tool.ruff]
cache-dir = ".cache/ruff"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
extend-include = [
    "*.ipynb",
]
line-length = 88
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = [
    "A",
    "ANN",
    "ARG",
    "B",
    "BLE",
    "C",
    "COM",
    "D",
    "DJ",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FBT",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
]
ignore = [
    "COM812",
    "E203",
    "E266",
    "E501",
    "E731",
    "E741",
    "F722",
    "FA102",
    "FBT001",
    "FBT002",
    "FIX002",
    "INP001",
    "ISC001",
    "PGH003",
    "TC002",
    "TD002",
    "TD003",
]
select = [
    "ALL",
]
unfixable = []

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.isort]
force-single-line = true
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 5
max-branches = 12
max-locals = 15
max-public-methods = 20
max-returns = 6
max-statements = 50
